[package]
name = "rosidl_runtime_rs"
version = "0.2.0"
authors = ["Jacob Hassold <jhassold@dcscorp.com>", "Nikolai Morin <nnmmgit@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

# Please keep the list of dependencies alphabetically sorted,
# and also state why each dependency is needed.
[dependencies]
# Needed for FFI
libc = "0.2"

[dev-dependencies]
# Needed for writing property tests
quickcheck = "1"