name: Rust Minimal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run the CI at 01:22 UTC every Tuesday
    # We pick an arbitrary time outside of most of the world's work hours
    # to minimize the likelihood of running alongside a heavy workload.
    - cron: '22 1 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        ros_distribution:
          - humble
          - jazzy
          - kilted
          - rolling
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
            ros_distribution: humble
            ros_version: 2
          # Jazzy Jalisco (May 2024 - May 2029)
          - docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-ros-base-latest
            ros_distribution: jazzy
            ros_version: 2
          # Kilted Kaiju (May 2025 - Dec 2026)
          - docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-kilted-ros-base-latest
            ros_distribution: kilted
            ros_version: 2
          # Rolling Ridley  (June 2020 - Present)
          - docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-rolling-ros-base-latest
            ros_distribution: rolling
            ros_version: 2

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ros_distribution == 'rolling' }}
    container:
      image: ${{ matrix.docker_image }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
        use-ros2-testing: ${{ matrix.ros_distribution == 'rolling' }}

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@1.75
      with:
        components: clippy, rustfmt

    - name: Test default features
      run: cargo test --workspace

    - name: Test with serde
      run: cargo test --workspace -F=serde

    - name: Build docs
      run: cargo doc --all-features
